-- ==============================================================================
-- ECTRON PRODUCTION CONTROL - SUPABASE SCHEMA SETUP
-- Run this in Supabase SQL Editor (https://supabase.com/dashboard/project/jmlpesgvewubbtsetkov/sql)
-- ==============================================================================

-- 1. USERS TABLE (جدول المستخدمين والفرق)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  company_id TEXT DEFAULT '',
  email TEXT DEFAULT '',
  phone TEXT DEFAULT '',
  access TEXT NOT NULL DEFAULT 'supervisor', -- 'admin', 'supervisor', 'viewer'
  team_name TEXT DEFAULT '',                 -- اسم الفريق
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- If users table already exists, make sure team_name column exists
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS team_name TEXT DEFAULT '';

-- 2. PRODUCTION RECORDS / FPY REPORTS TABLE (جدول سجلات الإنتاج والجودة)
CREATE TABLE IF NOT EXISTS public.production_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date TEXT NOT NULL,
  product TEXT DEFAULT 'Unknown',
  target INTEGER DEFAULT 320,
  overall_fpy NUMERIC,
  total_boards INTEGER DEFAULT 0,
  achieved INTEGER DEFAULT 0,
  updated_fw_qty INTEGER DEFAULT 0,          -- كمية الفيرموير المحدث يدوياً
  entered_by TEXT DEFAULT '',                -- اسم الشخص المدخل
  team_name TEXT DEFAULT '',                 -- اسم الفريق
  stations JSONB DEFAULT '[]'::jsonb,
  defects JSONB DEFAULT '[]'::jsonb,
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Backward compatibility view if any query targets fpy_reports
CREATE OR REPLACE VIEW public.fpy_reports AS 
SELECT * FROM public.production_records;

-- 3. STOPPAGES / DOWNTIME TABLE (جدول التوقفات)
CREATE TABLE IF NOT EXISTS public.stoppages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage_id TEXT NOT NULL,
  supervisor_id TEXT DEFAULT '',
  stopped_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  resumed_at TIMESTAMPTZ,
  reason_code TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-- Allow anon client to read and write records
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.production_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stoppages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anon full access on users" ON public.users;
CREATE POLICY "Anon full access on users" ON public.users 
  FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access on production_records" ON public.production_records;
CREATE POLICY "Anon full access on production_records" ON public.production_records 
  FOR ALL TO anon USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Anon full access on stoppages" ON public.stoppages;
CREATE POLICY "Anon full access on stoppages" ON public.stoppages 
  FOR ALL TO anon USING (true) WITH CHECK (true);

-- 5. INITIAL DEFAULT ADMIN USER (إذا لم يكن موجوداً)
INSERT INTO public.users (name, password, company_id, email, phone, access, team_name)
VALUES ('Admin', 'Admin@1234', 'ECTRON-001', 'admin@ectron.com', '', 'admin', 'Management')
ON CONFLICT (name) DO NOTHING;
