import { useState, useEffect, useCallback } from 'react';
import { supabase } from '../supabaseClient';
import { useAuth } from '../context/AuthContext';

const STAGES = [
  'Assembly',
  'Insulation',
  'RF',
  'Calibration',
  'Multin test',
  'Perso',
  'Packaging'
];

const STORAGE_KEY = 'ectron_active_downtime';

function formatMinutes(minutes) {
  if (minutes == null || isNaN(minutes)) return '0m';
  const hrs = Math.floor(minutes / 60);
  const mins = minutes % 60;
  if (hrs > 0 && mins > 0) return `${hrs}h ${mins}m`;
  if (hrs > 0) return `${hrs}h`;
  return `${mins}m`;
}

function formatElapsed(seconds) {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  const pad = (n) => String(n).padStart(2, '0');
  return `${pad(h)}:${pad(m)}:${pad(s)}`;
}

function getTodayString() {
  const now = new Date();
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

function getCurrentTimeString(dateObj = new Date()) {
  const hours = String(dateObj.getHours()).padStart(2, '0');
  const minutes = String(dateObj.getMinutes()).padStart(2, '0');
  return `${hours}:${minutes}`;
}

function computeDurationMinutes(start, end) {
  if (!start || !end) return 0;
  const [sh, sm] = start.split(':').map(Number);
  const [eh, em] = end.split(':').map(Number);
  if (isNaN(sh) || isNaN(sm) || isNaN(eh) || isNaN(em)) return 0;
  let s = sh * 60 + sm;
  let e = eh * 60 + em;
  if (e < s) e += 24 * 60;
  return e - s;
}

// ─── Downtime Report Modal (Prominently shows Name of User) ───────────────────
function DowntimeReportModal({ records, selectedDate, selectedStage, selectedUser, currentUser, onClose }) {
  const totalMinutes = records.reduce((acc, curr) => acc + (curr.total_minutes || 0), 0);

  // Breakdown by stage
  const stageBreakdown = STAGES.map(stageName => {
    const stageRecords = records.filter(r => r.stage === stageName);
    const mins = stageRecords.reduce((acc, curr) => acc + (curr.total_minutes || 0), 0);
    const count = stageRecords.length;
    return { stage: stageName, mins, count };
  }).filter(s => s.count > 0);

  function handlePrint() {
    window.print();
  }

  return (
    <div className="modal-backdrop" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal report-modal">
        <div className="modal-header">
          <span className="modal-title">Downtime Report Preview</span>
          <button className="modal-close" onClick={onClose}>×</button>
        </div>

        {/* Printable Document Area */}
        <div id="report-printable-area" className="report-document">
          {/* Header */}
          <div className="report-doc-header">
            <div className="report-logo-box">
              <img src="/ectron-logo.png" alt="ECTRON" className="report-logo-img" />
              <div style={{ fontSize: '0.8rem', color: 'var(--gray-500)', fontWeight: 600 }}>
                ECTRON PRODUCTION CONTROL SYSTEM
              </div>
            </div>
            <div className="report-title-box">
              <h1 className="report-main-title">Downtime Report</h1>
              <div className="report-subtitle">Official Production Downtime Summary</div>
            </div>
          </div>

          {/* Metadata Grid with User Name prominently displayed */}
          <div className="report-meta-grid">
            <div className="report-meta-item">
              <span className="report-meta-label">Generated By (User)</span>
              <span className="report-meta-value user-highlight">
                <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ color: 'var(--teal)' }}>
                  <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                  <circle cx="12" cy="7" r="4" />
                </svg>
                {currentUser?.name || 'Admin'}
              </span>
            </div>

            <div className="report-meta-item">
              <span className="report-meta-label">Company ID</span>
              <span className="report-meta-value">{currentUser?.company_id || 'ECTRON-001'}</span>
            </div>

            <div className="report-meta-item">
              <span className="report-meta-label">Report Period</span>
              <span className="report-meta-value">{selectedDate || 'All Recorded Dates'}</span>
            </div>

            <div className="report-meta-item">
              <span className="report-meta-label">Stage Filter</span>
              <span className="report-meta-value">{selectedStage || 'All Stages (1-7)'}</span>
            </div>

            <div className="report-meta-item">
              <span className="report-meta-label">Total Incidents</span>
              <span className="report-meta-value">{records.length} {records.length === 1 ? 'event' : 'events'}</span>
            </div>

            <div className="report-meta-item">
              <span className="report-meta-label">Total Downtime</span>
              <span className="report-meta-value" style={{ color: 'var(--teal-dark)' }}>
                {formatMinutes(totalMinutes)}
              </span>
            </div>
          </div>

          {/* Stage Breakdown Summary */}
          {stageBreakdown.length > 0 && (
            <div style={{ marginBottom: '20px' }}>
              <div className="report-section-title">Summary by Production Stage</div>
              <table className="report-table">
                <thead>
                  <tr>
                    <th>Stage</th>
                    <th style={{ textAlign: 'center' }}>Incidents</th>
                    <th style={{ textAlign: 'right' }}>Total Downtime</th>
                    <th style={{ textAlign: 'right' }}>Percentage</th>
                  </tr>
                </thead>
                <tbody>
                  {stageBreakdown.map(s => (
                    <tr key={s.stage}>
                      <td style={{ fontWeight: 600 }}>{s.stage}</td>
                      <td style={{ textAlign: 'center' }}>{s.count}</td>
                      <td style={{ textAlign: 'right', fontWeight: 600 }}>{formatMinutes(s.mins)}</td>
                      <td style={{ textAlign: 'right' }}>
                        {totalMinutes > 0 ? `${Math.round((s.mins / totalMinutes) * 100)}%` : '0%'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Detailed Log Table */}
          <div className="report-section-title">Detailed Downtime Events Log</div>
          {records.length === 0 ? (
            <div style={{ padding: '24px', textAlign: 'center', color: 'var(--gray-500)', fontSize: '0.85rem' }}>
              No downtime records found for the selected criteria.
            </div>
          ) : (
            <table className="report-table">
              <thead>
                <tr>
                  <th style={{ width: 35 }}>#</th>
                  <th>Date</th>
                  <th>User Name</th>
                  <th>Stage</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th style={{ textAlign: 'right' }}>Duration</th>
                </tr>
              </thead>
              <tbody>
                {records.map((r, i) => (
                  <tr key={r.id || i}>
                    <td>{i + 1}</td>
                    <td>{r.date}</td>
                    <td style={{ fontWeight: 700, color: 'var(--navy)' }}>{r.user_name}</td>
                    <td>{r.stage}</td>
                    <td>{r.start_time}</td>
                    <td>{r.end_time}</td>
                    <td style={{ textAlign: 'right', fontWeight: 700, color: 'var(--teal-dark)' }}>
                      {formatMinutes(r.total_minutes)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          {/* Official Sign-Off Block */}
          <div className="report-sign-block">
            <div className="sign-line">
              <span className="sign-line-title">Prepared By (User)</span>
              <div className="sign-line-placeholder">
                {currentUser?.name || 'Admin'}
              </div>
            </div>

            <div className="sign-line">
              <span className="sign-line-title">Production Supervisor</span>
              <div className="sign-line-placeholder"></div>
            </div>

            <div className="sign-line">
              <span className="sign-line-title">Date & Verification</span>
              <div className="sign-line-placeholder">
                {new Date().toLocaleDateString()}
              </div>
            </div>
          </div>
        </div>

        {/* Footer actions */}
        <div className="modal-footer">
          <button type="button" className="btn-secondary" onClick={onClose}>
            Close
          </button>
          <button type="button" className="btn-primary" onClick={handlePrint} style={{ display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="6 9 6 2 18 2 18 9" />
              <path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2" />
              <rect x="6" y="14" width="12" height="8" />
            </svg>
            <span>Print / Save as PDF</span>
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Manual / Edit Downtime Modal ─────────────────────────────────────────────
function DowntimeModal({ mode, initial, users, currentUserName, onClose, onSaved }) {
  const isEdit = mode === 'edit';
  const [user_name, setUserName] = useState(initial?.user_name || currentUserName || 'Admin');
  const [stage, setStage] = useState(initial?.stage || STAGES[0]);
  const [date, setDate] = useState(initial?.date || getTodayString());
  const [start_time, setStartTime] = useState(initial?.start_time || getCurrentTimeString());
  const [end_time, setEndTime] = useState(initial?.end_time || getCurrentTimeString());
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const durationMins = computeDurationMinutes(start_time, end_time);

  async function handleSubmit(e) {
    e.preventDefault();
    setError('');

    if (!stage || !date || !start_time || !end_time) {
      setError('Please fill in all required fields.');
      return;
    }

    setLoading(true);
    try {
      const durationMins = computeDurationMinutes(start_time, end_time);
      const payload = {
        id: isEdit ? initial.id : Date.now(),
        user_name,
        stage,
        date,
        start_time,
        end_time,
        total_minutes: durationMins
      };

      try {
        if (isEdit) {
          await supabase.from('stoppages').update({
            stage_id: stage,
            supervisor_id: user_name,
            notes: `${date} ${start_time} - ${end_time}`
          }).eq('id', initial.id);
        } else {
          await supabase.from('stoppages').insert([{
            stage_id: stage,
            supervisor_id: user_name,
            stopped_at: new Date(`${date}T${start_time}:00`).toISOString(),
            resumed_at: new Date(`${date}T${end_time}:00`).toISOString(),
            notes: `Downtime: ${durationMins}m`
          }]);
        }
      } catch (e) {
        console.warn('Supabase stoppage sync:', e);
      }

      onSaved(payload, isEdit);
    } catch (err) {
      setError(err?.message || 'Failed to save downtime record.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="modal-backdrop" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal">
        <div className="modal-header">
          <span className="modal-title">{isEdit ? 'Edit Downtime Record' : 'Manual Downtime Entry'}</span>
          <button className="modal-close" onClick={onClose} disabled={loading}>×</button>
        </div>

        <form onSubmit={handleSubmit}>
          <div className="modal-body">
            {error && <div className="modal-error">{error}</div>}

            <div className="form-group">
              <label>User *</label>
              <select
                className="form-select"
                value={user_name}
                onChange={e => setUserName(e.target.value)}
                disabled={loading}
              >
                {users.length > 0 ? (
                  users.map(u => (
                    <option key={u.id || u.name} value={u.name}>
                      {u.name} {u.company_id ? `(${u.company_id})` : ''}
                    </option>
                  ))
                ) : (
                  <option value={currentUserName || 'Admin'}>{currentUserName || 'Admin'}</option>
                )}
              </select>
            </div>

            <div className="form-group">
              <label>Stage *</label>
              <select
                className="form-select"
                value={stage}
                onChange={e => setStage(e.target.value)}
                disabled={loading}
              >
                {STAGES.map((s, idx) => (
                  <option key={s} value={s}>{idx + 1}. {s}</option>
                ))}
              </select>
            </div>

            <div className="form-group">
              <label>Date *</label>
              <input
                type="date"
                value={date}
                onChange={e => setDate(e.target.value)}
                disabled={loading}
                required
              />
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
              <div className="form-group">
                <label>Start Time *</label>
                <input
                  type="time"
                  value={start_time}
                  onChange={e => setStartTime(e.target.value)}
                  disabled={loading}
                  required
                />
              </div>

              <div className="form-group">
                <label>End Time *</label>
                <input
                  type="time"
                  value={end_time}
                  onChange={e => setEndTime(e.target.value)}
                  disabled={loading}
                  required
                />
              </div>
            </div>

            <div style={{
              background: 'var(--teal-light)',
              padding: '12px 14px',
              borderRadius: 'var(--radius)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              color: 'var(--navy)'
            }}>
              <span style={{ fontSize: '0.85rem', fontWeight: 600 }}>Calculated Duration:</span>
              <span style={{ fontSize: '1rem', fontWeight: 700, color: 'var(--teal-dark)' }}>
                {formatMinutes(durationMins)}
              </span>
            </div>
          </div>

          <div className="modal-footer">
            <button type="button" className="btn-secondary" onClick={onClose} disabled={loading}>
              Cancel
            </button>
            <button type="submit" className="btn-primary" disabled={loading}>
              {loading ? <span className="spinner" /> : isEdit ? 'Save Changes' : 'Save Record'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

// ─── Delete Confirm Modal ─────────────────────────────────────────────────────
function DeleteModal({ record, onClose, onDeleted }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function handleDelete() {
    setLoading(true);
    try {
      await supabase.from('stoppages').delete().eq('id', record.id);
      onDeleted(record.id);
    } catch (err) {
      setError(err?.message || 'Could not delete record.');
      setLoading(false);
    }
  }

  return (
    <div className="modal-backdrop" onClick={e => e.target === e.currentTarget && onClose()}>
      <div className="modal" style={{ maxWidth: 360 }}>
        <div className="modal-header">
          <span className="modal-title">Delete Record</span>
          <button className="modal-close" onClick={onClose} disabled={loading}>×</button>
        </div>

        <div className="modal-body" style={{ alignItems: 'center', textAlign: 'center', gap: 12 }}>
          <div className="confirm-icon">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="3 6 5 6 21 6" /><path d="M19 6l-1 14H6L5 6" />
              <path d="M10 11v6" /><path d="M14 11v6" /><path d="M9 6V4h6v2" />
            </svg>
          </div>
          <p className="confirm-msg">
            Delete downtime record for <span className="confirm-name">{record.stage}</span> on {record.date}?
          </p>
          {error && <div className="modal-error" style={{ width: '100%' }}>{error}</div>}
        </div>

        <div className="modal-footer">
          <button className="btn-secondary" onClick={onClose} disabled={loading}>Cancel</button>
          <button className="btn-danger" onClick={handleDelete} disabled={loading}>
            {loading ? <span className="spinner" style={{ borderTopColor: 'white' }} /> : 'Delete'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Main Downtime Page ───────────────────────────────────────────────────────
export default function Downtime() {
  const { user } = useAuth();
  const isViewer = user?.access === 'viewer';

  const [records, setRecords] = useState([]);
  const [users, setUsers] = useState([]);
  const [selectedDate, setSelectedDate] = useState(getTodayString());
  const [selectedStage, setSelectedStage] = useState('');
  const [selectedUser, setSelectedUser] = useState('');
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null); // null | { type: 'add'|'edit'|'delete'|'report', record? }
  const [toast, setToast] = useState('');

  // ─── Easy Live Recording State ──────────────────────────────────────────────
  const [selectedPillStage, setSelectedPillStage] = useState(STAGES[0]);
  const [activeSession, setActiveSession] = useState(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  });
  const [elapsedSeconds, setElapsedSeconds] = useState(0);
  const [isSavingLive, setIsSavingLive] = useState(false);

  // Timer ticker
  useEffect(() => {
    if (!activeSession) {
      setElapsedSeconds(0);
      return;
    }

    const updateTimer = () => {
      const diff = Math.max(0, Math.floor((Date.now() - activeSession.startTimestamp) / 1000));
      setElapsedSeconds(diff);
    };

    updateTimer();
    const interval = setInterval(updateTimer, 1000);
    return () => clearInterval(interval);
  }, [activeSession]);

  // Fetch users
  useEffect(() => {
    supabase.from('users').select('*')
      .then(res => setUsers(res.data || []))
      .catch(() => {});
  }, []);

  // Fetch downtime records
  const fetchRecords = useCallback(async () => {
    setLoading(true);
    try {
      const { data, error } = await supabase.from('stoppages').select('*').order('stopped_at', { ascending: false });
      let list = (data || []).map(s => {
        const start = s.stopped_at ? new Date(s.stopped_at) : new Date();
        const end = s.resumed_at ? new Date(s.resumed_at) : new Date();
        const dateStr = start.toISOString().slice(0, 10);
        const startTimeStr = start.toTimeString().slice(0, 5);
        const endTimeStr = end.toTimeString().slice(0, 5);
        const diffMins = Math.max(1, Math.floor((end.getTime() - start.getTime()) / 60000));
        return {
          id: s.id,
          user_name: s.supervisor_id || 'Supervisor',
          stage: s.stage_id,
          date: dateStr,
          start_time: startTimeStr,
          end_time: endTimeStr,
          total_minutes: diffMins
        };
      });

      if (selectedDate) list = list.filter(r => r.date === selectedDate);
      if (selectedStage) list = list.filter(r => r.stage === selectedStage);
      if (selectedUser) list = list.filter(r => r.user_name === selectedUser);
      setRecords(list);
    } catch {
      // handled
    } finally {
      setLoading(false);
    }
  }, [selectedDate, selectedStage, selectedUser]);

  useEffect(() => {
    fetchRecords();
  }, [fetchRecords]);

  // Total downtime in selected day
  const totalMinutesInDay = records.reduce((acc, curr) => acc + (curr.total_minutes || 0), 0);

  // ─── Start Live Downtime ────────────────────────────────────────────────────
  function handleStartLiveDowntime() {
    const now = new Date();
    const session = {
      stage: selectedPillStage,
      user_name: user?.name || 'Admin',
      date: getTodayString(),
      start_time: getCurrentTimeString(now),
      startTimestamp: Date.now()
    };
    localStorage.setItem(STORAGE_KEY, JSON.stringify(session));
    setActiveSession(session);
    showToast(`Downtime recording started for "${selectedPillStage}"`);
  }

  // ─── Stop & Save Live Downtime ──────────────────────────────────────────────
  async function handleStopAndSaveLiveDowntime() {
    if (!activeSession) return;
    setIsSavingLive(true);

    try {
      const now = new Date();
      let end_time = getCurrentTimeString(now);

      if (end_time === activeSession.start_time && elapsedSeconds >= 30) {
        const nextMin = new Date(now.getTime() + 60000);
        end_time = getCurrentTimeString(nextMin);
      }

      const durationMins = Math.max(1, Math.ceil(elapsedSeconds / 60));
      const payload = {
        id: Date.now(),
        user_name: activeSession.user_name,
        stage: activeSession.stage,
        date: activeSession.date,
        start_time: activeSession.start_time,
        end_time: end_time,
        total_minutes: durationMins
      };

      try {
        await supabase.from('stoppages').insert([{
          stage_id: activeSession.stage,
          supervisor_id: activeSession.user_name,
          stopped_at: new Date(activeSession.startTimestamp).toISOString(),
          resumed_at: now.toISOString(),
          notes: `Live session: ${durationMins}m`
        }]);
      } catch (e) {
        console.warn('Supabase live save error:', e);
      }

      localStorage.removeItem(STORAGE_KEY);
      setActiveSession(null);
      setElapsedSeconds(0);
      showToast(`Saved downtime for "${payload.stage}" (${payload.start_time} - ${payload.end_time})!`);
      fetchRecords();
    } catch (err) {
      alert(err?.message || 'Error saving downtime record.');
    } finally {
      setIsSavingLive(false);
    }
  }

  // ─── Cancel Live Session ────────────────────────────────────────────────────
  function handleCancelLiveDowntime() {
    if (window.confirm('Cancel this recording without saving?')) {
      localStorage.removeItem(STORAGE_KEY);
      setActiveSession(null);
      setElapsedSeconds(0);
      showToast('Recording cancelled.');
    }
  }

  function showToast(msg) {
    setToast(msg);
    setTimeout(() => setToast(''), 4000);
  }

  function onSaved() {
    setModal(null);
    fetchRecords();
    showToast('Record saved successfully.');
  }

  function onDeleted(id) {
    setRecords(prev => prev.filter(r => r.id !== id));
    setModal(null);
    fetchRecords();
    showToast('Record deleted.');
  }

  return (
    <div>
      {/* Toast Alert */}
      {toast && (
        <div style={{
          position: 'fixed',
          top: '24px',
          right: '24px',
          background: 'var(--navy)',
          color: 'var(--white)',
          padding: '12px 20px',
          borderRadius: '8px',
          boxShadow: 'var(--shadow-lg)',
          zIndex: 9999,
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          fontSize: '0.9rem',
          fontWeight: 600,
          animation: 'fadeIn 0.2s ease'
        }}>
          <span style={{ color: 'var(--teal)' }}>✔</span>
          {toast}
        </div>
      )}

      {/* Page Header */}
      <div className="page-header">
        <h1 className="page-title">Downtime</h1>
        <p className="page-subtitle">Track and record downtime across the 7 production stages</p>
      </div>

      {/* ─── VIEWER READ-ONLY NOTICE OR LIVE TRACKER ─── */}
      {isViewer ? (
        <div style={{
          background: 'var(--white)',
          border: '1.5px solid var(--gray-200)',
          borderRadius: '12px',
          padding: '16px 20px',
          marginBottom: '24px',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          boxShadow: 'var(--shadow-sm)'
        }}>
          <span className="badge badge-viewer" style={{ padding: '5px 12px', fontSize: '0.8rem' }}>
            Viewer Mode
          </span>
          <span style={{ fontSize: '0.875rem', color: 'var(--gray-700)' }}>
            Signed in as <strong>{user?.name}</strong> (Read-Only). You can view all downtime records and generate reports. Downtime recording is restricted to Supervisors and Admins.
          </span>
        </div>
      ) : (
        <div className={`tracker-card ${activeSession ? 'active' : ''}`}>
        <div className="tracker-header">
          <div className="tracker-title">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ color: 'var(--teal)' }}>
              <circle cx="12" cy="12" r="10" />
              <polyline points="12 6 12 12 16 14" />
            </svg>
            <span>Easy Downtime Recorder</span>
          </div>

          <div style={{ fontSize: '0.85rem', color: 'var(--gray-500)' }}>
            Logged in as: <strong style={{ color: 'var(--navy)' }}>{user?.name || 'Admin'}</strong>
          </div>
        </div>

        {!activeSession ? (
          <div>
            <div style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--gray-700)', marginBottom: '10px' }}>
              Select Stage to Start Downtime:
            </div>

            <div className="stage-pills">
              {STAGES.map((s, idx) => (
                <button
                  key={s}
                  type="button"
                  className={`stage-pill ${selectedPillStage === s ? 'selected' : ''}`}
                  onClick={() => setSelectedPillStage(s)}
                >
                  <span className="stage-pill-num">{idx + 1}</span>
                  <span>{s}</span>
                </button>
              ))}
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap' }}>
              <button
                type="button"
                className="btn-start-downtime"
                onClick={handleStartLiveDowntime}
              >
                <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                  <polygon points="5 3 19 12 5 21 5 3" />
                </svg>
                <span>Start Downtime ({selectedPillStage})</span>
              </button>

              <span style={{ fontSize: '0.825rem', color: 'var(--gray-500)' }}>
                Click to start recording timer immediately.
              </span>
            </div>
          </div>
        ) : (
          <div className="tracker-running-box">
            <div className="tracker-running-info">
              <div className="live-pulse">
                <span className="pulse-dot" />
                <span>Recording in progress</span>
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginTop: '4px' }}>
                <span style={{
                  background: 'var(--navy)',
                  color: 'var(--white)',
                  padding: '4px 12px',
                  borderRadius: '16px',
                  fontSize: '0.85rem',
                  fontWeight: 700
                }}>
                  {activeSession.stage}
                </span>
                <span style={{ fontSize: '0.85rem', color: 'var(--gray-500)' }}>
                  Started at <strong>{activeSession.start_time}</strong> by <strong style={{ color: 'var(--navy)' }}>{activeSession.user_name}</strong>
                </span>
              </div>
            </div>

            <div style={{ display: 'flex', alignItems: 'center', gap: '20px', flexWrap: 'wrap' }}>
              <div className="stopwatch-display">
                {formatElapsed(elapsedSeconds)}
              </div>

              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <button
                  type="button"
                  className="btn-stop-downtime"
                  onClick={handleStopAndSaveLiveDowntime}
                  disabled={isSavingLive}
                >
                  {isSavingLive ? (
                    <span className="spinner" />
                  ) : (
                    <>
                      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">
                        <rect x="4" y="4" width="16" height="16" rx="2" />
                      </svg>
                      <span>Stop & Save Record</span>
                    </>
                  )}
                </button>

                <button
                  type="button"
                  className="btn-secondary"
                  style={{ padding: '12px 16px' }}
                  onClick={handleCancelLiveDowntime}
                  disabled={isSavingLive}
                  title="Cancel without saving"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
      )}

      {/* Summary Cards */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
        gap: '16px',
        marginBottom: '24px'
      }}>
        <div style={{
          background: 'var(--white)',
          padding: '20px',
          borderRadius: '12px',
          border: '1px solid var(--gray-200)',
          boxShadow: 'var(--shadow-sm)',
          display: 'flex',
          alignItems: 'center',
          gap: '16px'
        }}>
          <div style={{
            width: '48px',
            height: '48px',
            borderRadius: '10px',
            background: 'rgba(0, 175, 170, 0.12)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'var(--teal)'
          }}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="10" />
              <polyline points="12 6 12 12 16 14" />
            </svg>
          </div>
          <div>
            <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--gray-500)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Total Downtime ({selectedDate || 'All Dates'})
            </div>
            <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--navy)', marginTop: '2px' }}>
              {formatMinutes(totalMinutesInDay)}
            </div>
          </div>
        </div>

        <div style={{
          background: 'var(--white)',
          padding: '20px',
          borderRadius: '12px',
          border: '1px solid var(--gray-200)',
          boxShadow: 'var(--shadow-sm)',
          display: 'flex',
          alignItems: 'center',
          gap: '16px'
        }}>
          <div style={{
            width: '48px',
            height: '48px',
            borderRadius: '10px',
            background: 'rgba(35, 63, 121, 0.1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: 'var(--navy)'
          }}>
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="3" y="4" width="18" height="18" rx="2" ry="2" />
              <line x1="16" y1="2" x2="16" y2="6" />
              <line x1="8" y1="2" x2="8" y2="6" />
              <line x1="3" y1="10" x2="21" y2="10" />
            </svg>
          </div>
          <div>
            <div style={{ fontSize: '0.8rem', fontWeight: 600, color: 'var(--gray-500)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              Records Count
            </div>
            <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--navy)', marginTop: '2px' }}>
              {records.length} {records.length === 1 ? 'event' : 'events'}
            </div>
          </div>
        </div>
      </div>

      {/* Toolbar / Filters + Report Button */}
      <div className="users-toolbar">
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
          <div className="form-group" style={{ margin: 0 }}>
            <input
              type="date"
              className="search-input"
              style={{ padding: '8px 12px', minWidth: '150px' }}
              value={selectedDate}
              onChange={e => setSelectedDate(e.target.value)}
            />
          </div>

          <div className="form-group" style={{ margin: 0 }}>
            <select
              className="form-select"
              style={{ padding: '8px 32px 8px 12px', minWidth: '150px' }}
              value={selectedStage}
              onChange={e => setSelectedStage(e.target.value)}
            >
              <option value="">All Stages (1-7)</option>
              {STAGES.map((s, idx) => (
                <option key={s} value={s}>{idx + 1}. {s}</option>
              ))}
            </select>
          </div>

          <div className="form-group" style={{ margin: 0 }}>
            <select
              className="form-select"
              style={{ padding: '8px 32px 8px 12px', minWidth: '140px' }}
              value={selectedUser}
              onChange={e => setSelectedUser(e.target.value)}
            >
              <option value="">All Users</option>
              {users.map(u => (
                <option key={u.id || u.name} value={u.name}>{u.name}</option>
              ))}
            </select>
          </div>

          {selectedDate && (
            <button
              className="btn-secondary"
              style={{ padding: '8px 12px', fontSize: '0.8125rem' }}
              onClick={() => setSelectedDate('')}
            >
              Show All Dates
            </button>
          )}
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginLeft: 'auto' }}>
          {/* Report Button */}
          <button
            type="button"
            className="btn-primary"
            style={{ background: 'var(--navy)', display: 'flex', alignItems: 'center', gap: '7px' }}
            onClick={() => setModal({ type: 'report' })}
          >
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
              <polyline points="14 2 14 8 20 8" />
              <line x1="16" y1="13" x2="8" y2="13" />
              <line x1="16" y1="17" x2="8" y2="17" />
              <polyline points="10 9 9 9 8 9" />
            </svg>
            <span>View / Print Report</span>
          </button>

          {/* Manual Entry (hidden for Viewers) */}
          {!isViewer && (
            <button
              type="button"
              className="btn-secondary"
              onClick={() => setModal({ type: 'add' })}
              style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
            >
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="12" y1="5" x2="12" y2="19" /><line x1="5" y1="12" x2="19" y2="12" />
              </svg>
              <span>Manual Entry</span>
            </button>
          )}
        </div>
      </div>

      {/* Table */}
      <div className="table-card">
        <div className="table-wrap">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>User</th>
                <th>Stage</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Total Time</th>
                <th style={{ width: 80, textAlign: 'center' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="7" className="table-empty">
                    <span className="spinner" style={{ borderColor: 'rgba(0,175,170,.2)', borderTopColor: 'var(--teal)' }} />
                  </td>
                </tr>
              ) : records.length === 0 ? (
                <tr>
                  <td colSpan="7" className="table-empty">
                    No downtime recorded {selectedDate ? `for ${selectedDate}` : ''}.
                  </td>
                </tr>
              ) : (
                records.map(r => (
                  <tr key={r.id}>
                    <td style={{ fontWeight: 500 }}>{r.date}</td>
                    <td style={{ fontWeight: 700, color: 'var(--navy)' }}>
                      <span style={{ display: 'inline-flex', alignItems: 'center', gap: '5px' }}>
                        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ opacity: 0.6 }}>
                          <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2" />
                          <circle cx="12" cy="7" r="4" />
                        </svg>
                        {r.user_name}
                      </span>
                    </td>
                    <td>
                      <span className="badge badge-user" style={{ background: 'rgba(35, 63, 121, 0.1)', color: 'var(--navy)' }}>
                        {r.stage}
                      </span>
                    </td>
                    <td>{r.start_time}</td>
                    <td>{r.end_time}</td>
                    <td>
                      <strong style={{ color: 'var(--teal-dark)' }}>
                        {formatMinutes(r.total_minutes)}
                      </strong>
                    </td>
                    <td>
                      {!isViewer ? (
                        <div className="action-btns" style={{ justifyContent: 'center' }}>
                          <button
                            className="btn-icon btn-edit"
                            title="Edit"
                            onClick={() => setModal({ type: 'edit', record: r })}
                          >
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                            </svg>
                          </button>
                          <button
                            className="btn-icon btn-delete"
                            title="Delete"
                            onClick={() => setModal({ type: 'delete', record: r })}
                          >
                            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                              <polyline points="3 6 5 6 21 6" /><path d="M19 6l-1 14H6L5 6" />
                              <path d="M10 11v6" /><path d="M14 11v6" /><path d="M9 6V4h6v2" />
                            </svg>
                          </button>
                        </div>
                      ) : (
                        <div style={{ textAlign: 'center', fontSize: '0.75rem', color: 'var(--gray-500)' }}>
                          Read only
                        </div>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        {!loading && records.length > 0 && (
          <div className="table-count" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
            <span>{records.length} {records.length === 1 ? 'record' : 'records'}</span>
            <span>
              Total time in day: <strong style={{ color: 'var(--navy)', marginLeft: '4px' }}>{formatMinutes(totalMinutesInDay)}</strong>
            </span>
          </div>
        )}
      </div>

      {/* Modals */}
      {modal?.type === 'report' && (
        <DowntimeReportModal
          records={records}
          selectedDate={selectedDate}
          selectedStage={selectedStage}
          selectedUser={selectedUser}
          currentUser={user}
          onClose={() => setModal(null)}
        />
      )}

      {modal?.type === 'add' && (
        <DowntimeModal
          mode="add"
          users={users}
          currentUserName={user?.name}
          onClose={() => setModal(null)}
          onSaved={onSaved}
        />
      )}

      {modal?.type === 'edit' && (
        <DowntimeModal
          mode="edit"
          initial={modal.record}
          users={users}
          currentUserName={user?.name}
          onClose={() => setModal(null)}
          onSaved={onSaved}
        />
      )}

      {modal?.type === 'delete' && (
        <DeleteModal
          record={modal.record}
          onClose={() => setModal(null)}
          onDeleted={onDeleted}
        />
      )}
    </div>
  );
}
